tests: fix flaky pkg.bugtool.TestFindMaps
We had a few failures in the CI from times to times with:

	maps_test.go:48:
		Error Trace:	/home/runner/work/tetragon/tetragon/go/src/github.com/cilium/tetragon/pkg/bugtool/maps_test.go:48
		Error:      	Should not be zero, but was 0
		Test:       	TestFindMaps/BaseSensorMemlock

Showing that this part of the test was sometime failing:

	mapsUsedByProgs, err := FindMapsUsedByPinnedProgs(path)
	require.NoError(t, err)
	if assert.NotEmpty(t, mapsUsedByProgs) {
		assert.NotZero(t, mapsUsedByProgs[0].Memlock)
	}

I didn't think that memlock could be zero on a map. From the kernel it's
now calculated per map type by using the map_mem_usage function pointer
and it appears from the failures above that we observe, that in some
situations, some of these functions can return zero. Let's decrease the
probability we run into this by summing all the memlock of the maps we
observe instead of blindly taking the first one.

Signed-off-by: Mahe Tardy <mahe.tardy@gmail.com>